# Generated by Django 3.0.2 on 2020-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('image_slug', models.SlugField()),
                ('image_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
