# Generated by Django 3.0.2 on 2020-01-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0003_image_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='author',
            new_name='image_user',
        ),
    ]
