# Generated by Django 3.0.2 on 2020-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0004_auto_20200115_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(height_field='image_height', upload_to='media/', width_field='image_width'),
        ),
    ]
