# Generated by Django 3.0.2 on 2020-01-15 19:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_image', '0005_auto_20200115_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='User_Image',
        ),
    ]
